-- RELATÓRIO 1: CONSULTA DE DADOS
-- 1
SELECT 
    P.NM_PACIENTE,
    TO_CHAR(C.DT_HR_CONSULTA, 'DD/MM/YYYY HH24:MI') AS DATA_CONSULTA
FROM 
    T_HC_PACIENTE P
JOIN 
    T_HC_CONSULTA C ON P.ID_PACIENTE = C.ID_PACIENTE
ORDER BY 
    C.DT_HR_CONSULTA ASC;
-- 2
SELECT 
    ID_PACIENTE,
    NM_PACIENTE,
    NR_CPF,
    DT_NASCIMENTO
FROM 
    T_HC_PACIENTE
ORDER BY 
    NM_PACIENTE ASC;

-- RELATÓRIO 2: CONSULTA COM RETORNO NUMERICO
-- 1
SELECT 
    COUNT(*) AS TOTAL_CONSULTAS
FROM 
    T_HC_CONSULTA;

-- 2
SELECT 
    ROUND(AVG(TRUNC(MONTHS_BETWEEN(SYSDATE, DT_NASCIMENTO) / 12)), 1) AS IDADE_MEDIA
FROM 
    T_HC_PACIENTE;
    
-- RELATÓRIO 3: CONSULTA DE GRUPO
--1 
SELECT 
    DS_MODALIDADE,
    COUNT(*) AS TOTAL
FROM 
    T_HC_CONSULTA
GROUP BY 
    DS_MODALIDADE;
    
--2
SELECT 
    M.NM_MEDICO,
    COUNT(C.ID_CONSULTA) AS TOTAL_CONSULTAS
FROM 
    T_HC_CONSULTA C
JOIN 
    T_HC_MEDICO M ON C.ID_MEDICO = M.ID_MEDICO
GROUP BY 
    M.NM_MEDICO
ORDER BY 
    TOTAL_CONSULTAS DESC;

-- RELATÓRIO 4: SUBCONSULTA
--1 
SELECT 
    DISTINCT M.NM_MEDICO,
    M.NR_CRM
FROM 
    T_HC_MEDICO M
WHERE 
    M.ID_MEDICO IN (
        SELECT C.ID_MEDICO
        FROM T_HC_CONSULTA C
        WHERE C.ID_PACIENTE IN (
            SELECT E.ID_PACIENTE
            FROM T_HC_ENDERECO E
            WHERE E.SG_ESTADO = 'SP'
        )
    )
ORDER BY 
    M.NM_MEDICO;
    
--2 
SELECT 
    NM_PACIENTE,
    NR_CPF,
    DS_ESTADO_CIVIL
FROM 
    T_HC_PACIENTE
WHERE 
    ID_PACIENTE IN (
        SELECT ID_PACIENTE
        FROM T_HC_LEMBRETE
    )
ORDER BY 
    NM_PACIENTE;

-- RELATÓRIO 5: JUNÇÃO DE TABELAS
--1
SELECT 
    C.ID_CONSULTA,
    TO_CHAR(C.DT_HR_CONSULTA, 'DD/MM/YYYY HH24:MI') AS DATA_CONSULTA,
    P.NM_PACIENTE,
    M.NM_MEDICO,
    M.NR_CRM,
    C.DS_MODALIDADE
FROM 
    T_HC_CONSULTA C
JOIN 
    T_HC_PACIENTE P ON C.ID_PACIENTE = P.ID_PACIENTE
JOIN 
    T_HC_MEDICO M ON C.ID_MEDICO = M.ID_MEDICO;
    
-- 2
SELECT 
    P.ID_PACIENTE,
    P.NM_PACIENTE,
    E.NM_CIDADE,
    E.SG_ESTADO,
    T.NR_DDD,
    T.NR_TELEFONE
FROM 
    T_HC_PACIENTE P
JOIN 
    T_HC_ENDERECO E ON P.ID_PACIENTE = E.ID_PACIENTE
JOIN 
    T_HC_TELEFONE T ON P.ID_PACIENTE = T.ID_PACIENTE
ORDER BY 
    P.NM_PACIENTE;
